### PR TITLE
Play menu music 9

### PR DESCRIPTION
**Pull request by Marty99-dev**

### CODE REVIEW

**Review by JorisMonnet — CHANGES_REQUESTED** [review]
You should add some checks in tests

**Review by ghemDD — COMMENTED** [review]
Nice changes 
Manage lifecycles (onPause, onResume...)
Use MusicViewModel

**Comment by Marty99-dev** [comment]
> Nice changes Manage lifecycles (onPause, onResume...) Use MusicViewModel

I'll upgrade my code in my next PR!

**Review by marluxiaboss — APPROVED** [review]
Nice music! It should be better also to pause the music when previewing another music.

**Review by JorisMonnet — APPROVED** [review]

**Pull request merged**
