### PR TITLE
Change the music layer

### PR DESCRIPTION
**Pull request by Marty99-dev**

### CODE REVIEW

**Review by kapapp — APPROVED** [review]
Thanks for the commentary:) Seems like a good idea to have a fetcher/ressourceFetcher class

**Review by marluxiaboss — APPROVED** [review]
Code lacks documentation.

**Review by ghemDD — APPROVED** [review]
Nice cleaning

**Comment by Marty99-dev** [comment]
> Code lacks documentation.

I will take time during my sprint to document my code ! But good remark.

**Comment by Marty99-dev** [comment]
> Nice cleaning

Based on our discussion ;)

**Comment by JorisMonnet** [comment]
there is a lot of warnings in Gamesound

**Comment by Marty99-dev** [comment]
> there is a lot of warnings in Gamesound

I'll correct them today if I can !

**Pull request merged**
